#!/usr/bin/env bash

# Stop on first error
set -e

# Create a host for our docker container
if !(docker-machine ls | grep "^rcs-docs "); then
  docker-machine create --driver virtualbox rcs-docs
fi

# Start the host
if (docker-machine ls | grep "^rcs-docs .* Stopped"); then
  docker-machine start rcs-docs
fi

# Load our docker machine's environment variables
eval $(docker-machine env rcs-docs --shell bash)

# Build a new image that will build and serve our jekyll content
docker build --tag rcs-docs --file script/Dockerfile .

# Remove dangling images from previous runs
docker rmi -f $(docker images --filter "dangling=true" -q) > /dev/null 2>&1 || true

echo "***********************************************************"
echo "  Your site is available at http://$(docker-machine ip rcs-docs):4000"
echo "***********************************************************"

# Serve up the content and watch for changes
# The extra '/' is to make volume work on windows
docker run --rm \
  --volume=/$(pwd):/src \
  --publish 4000:4000 \
  rcs-docs \
  serve --watch --drafts --force_polling -H 0.0.0.0
